### PR TITLE
Implement extended user creation and password recovery APIs

### PR DESCRIPTION
**Pull request by niklasb**
to implement user creation with asset IDs and password recovery, allowing arbitrary JSON objects in API requests is required. This PR implements this and the mentioned APIs on top of it.

### CODE REVIEW

**Comment by carlio** [comment]
Could you make this an optional dependency please? The PyNaCL dependency alone has various system dependencies I believe which could cause CI/CD for people not expecting it to break if we include it as a default.

Ideally moving those dependencies to the `_OPTIONAL_REQUIRES['raw_recovery_kit']` then the library can be installed with something like `pip install upvest[raw_recovery_kit]` or something.

That'd also require various places where `nacl` and `protobuf` is imported to have some try/except ImportError but I think it'd be better to keep the basic library lightweight and also not break anything for existing users.

I'm happy to do this myself and create a PR for your PR (inception...) if you like.

**Comment by niklasb** [comment]
@carlio that makes sense, and it was a pretty minimal change.

**Comment by carlio** [comment]
Cool, thanks @niklasb . I'll make a new release later today after merging in some of my local changes too.

**Comment by carlio** [comment]
@niklasb got our CI config working correctly with the new tests, so `0.0.8` is now on PyPI 👍

**Pull request merged**
